I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/school.rpy", line 199, in script
    if date_this_weekend:
  File "game/school.rpy", line 199, in <module>
    if date_this_weekend:
NameError: name 'date' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/school.rpy", line 199, in script
    if date_this_weekend:
  File "C:\Users\Kim\Desktop\renpy-8.0.3-sdk\renpy\ast.py", line 2115, in execute
    if renpy.python.py_eval(condition):
  File "C:\Users\Kim\Desktop\renpy-8.0.3-sdk\renpy\python.py", line 1092, in py_eval
    return py_eval_bytecode(code, globals, locals)
  File "C:\Users\Kim\Desktop\renpy-8.0.3-sdk\renpy\python.py", line 1085, in py_eval_bytecode
    return eval(bytecode, globals, locals)
  File "game/school.rpy", line 199, in <module>
    if date_this_weekend:
NameError: name 'date' is not defined

Windows-10-10.0.22000 AMD64
Ren'Py 8.0.3.22090809
Call It Fate 1.0
Mon Jan 30 19:18:37 2023
