I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/maddie.rpy", line 169, in script
    if fluffy:
  File "game/maddie.rpy", line 169, in <module>
    if fluffy:
NameError: name 'fluffy' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/maddie.rpy", line 169, in script
    if fluffy:
  File "C:\Users\Kim\Desktop\renpy-8.0.3-sdk\renpy\ast.py", line 2115, in execute
    if renpy.python.py_eval(condition):
  File "C:\Users\Kim\Desktop\renpy-8.0.3-sdk\renpy\python.py", line 1092, in py_eval
    return py_eval_bytecode(code, globals, locals)
  File "C:\Users\Kim\Desktop\renpy-8.0.3-sdk\renpy\python.py", line 1085, in py_eval_bytecode
    return eval(bytecode, globals, locals)
  File "game/maddie.rpy", line 169, in <module>
    if fluffy:
NameError: name 'fluffy' is not defined

Windows-10-10.0.22621 AMD64
Ren'Py 8.0.3.22090809
Call It Fate 1.0
Wed Mar 15 13:58:41 2023
